baseurl      = "mihai.lupoiu.com"
title        = "Mihai Lupoiu"
languageCode = "en-us"
theme        = "hello-friend-ng"

paginate     = 10
rssLimit  = 10  # Maximum number of items in the RSS feed.

enableEmoji     = true

[permalinks]
  posts = "/posts/:year/:month/:title/"

[author]
  name = "Mihai Lupoiu"

[params]
  dateform        = "May 23, 2023"
  dateformShort   = "May 23"
  dateformNum     = "2023-05-23"
  dateformNumTime = "2023-05-23 15:04"

  # Subtitle for home
  homeSubtitle = "Software Engineer"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true
  
  # Show a global language switcher in the navigation bar
  enableGlobalLanguageMenu = false

  enableThemeToggle = true

  # Metadata mostly used in document's head
  description = "My new homepage or blog"
  keywords = "homepage, blog"
  images = [""]
  
  # Social icons
  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/mihailupoiu"

  [[params.social]]
    name = "email"
    url  = "mailto:myhay.360@gmail.com"

  [[params.social]]
    name = "github"
    url  = "https://github.com/mihailupoiu"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/mihailupoiu/"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Mihai Lupoiu"
    subtitle = "A simple theme for Hugo"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "$ cd /home/"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # Custom footer 
  # If you want, you can easily override the default footer with your own content. 
  #
  [params.footer]
    trademark = true
    rss = true
    copyright = true
    author = true

    topText = []
    bottomText = [
      "Powered by <a href=\"http://gohugo.io\">Hugo</a>",
      "Made with &#10084; by <a href=\"https://github.com/rhazdon\">Djordje Atlialp</a>"
    ]

  # And you can even create generic menu
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about/"
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"
  [[menu.main]]
    identifier = "docs"
    name       = "Docs"
    url        = "/docs"
  [[menu.main]]
    identifier = "tests"
    name       = "Tests"
    url        = "/Tests"